### ISSUE TITLE
Loading more?

### ISSUE THREAD

**Issue by xq598359628** [Cleveroad/FireworkyPullToRefresh#11]
can you add the function of loading more?

**Comment by ValeryGes** [comment]
Hi, @xq598359628, Thank you for using our library!
The library presented here is custom PullToRefreshLayout. The implementation of items loading is just an example for better visualization of library setup, configuration and using. You can write your own implementation for loading with pagination in your project.

If you had something else in mind by asking this question, do not hesitate to clarify it here.

With best regards, Cleveroad Team!
