### ISSUE TITLE
Stuck or remains white space if change fragment

### ISSUE THREAD

**Issue by wondersoftwares671** [Cleveroad/FireworkyPullToRefresh#13]
I have 4 fragments in my activity and all have FireworkyPullToRefresh View in it. When i pull down and start Loading and change the fragment then this view or white space use by loading view will stuck at it's position.
I have tried to setRefreshing false at fragment's onStop() method but still no luck. :(

I have to replace this view with traditional pulltorefresh view that i don't want.
By the way cheers for the work. 👍 
Thanks!

**Comment by ValeryGes** [comment]
Hi, @wondersoftwares671,

Thank you for using FireworkyPullToRefresh. Can you provide your xml and java code here. And we will investigate this issue and fix it if problem is in our library or we show you where the problem is.

With best regards, Cleveroad Team!

**Comment by yarovoiag** [comment]
Hi, @wondersoftwares671 , could you provide more details ?
