### ISSUE TITLE
how to change offset color  or delete it 

### ISSUE THREAD

**Issue by mohamedamineamdouni** [Cleveroad/FireworkyPullToRefresh#4]
![14522195_1536502903042286_951150097_o](https://cloud.githubusercontent.com/assets/18621393/19025794/b39e2cfa-8915-11e6-873e-841264ed4c81.jpg)

**Comment by ilchenko-peter** [comment]
Hi @mohamedamineamdouni ,
we're looking at this problem.

**Comment by mohamedamineamdouni** [comment]
thank's @ilchenko-peter

**Comment by ilchenko-peter** [comment]
This issue was resolved in version **1.0.2**
